plugins {
    id "com.android.application"
}
android {
    namespace "app.myousic"
    compileSdk 34
    defaultConfig {
        applicationId "app.myousic"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
}
