apply plugin: "com.android.application"

android {
    namespace "app.myousic"
    compileSdk 33
    defaultConfig {
        applicationId "app.myousic"
        minSdk 24
        targetSdk 33
        versionCode 4
        versionName "1.3"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}
